spring:
  application:
    name: catalog
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/"
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
