server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: catalog module
          uri: http://catalog:8080
          predicates:
            - Path=/products/**
        - id: discovery module
          uri: http://discovery:8761
          predicates:
            - Path=/eureka-ui/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/