# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package
      
    - name: jacoco-badge-generator
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.3.0
      with:
        jacoco-csv-file: catalog/target/site/jacoco/jacoco.csv
    
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        
    - name: Create pull request
      if: ${{ github.event_name == 'push' }}
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        title: "Autogenerated Jacoco Coverage Badge"
        body: > 
          Autogenerated Jacoco coverage badge, generated by 
          the [jacoco-badge-generator](https://github.com/cicirello/jacoco-badge-generator) 
          GitHub action.  Automated pull-request generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request) 
          GitHub action.
        commit-message: "Autogenerated Jacoco Coverage Badge"
        author: Vincent A Cicirello <cicirello@users.noreply.github.com>
        committer: Vincent A Cicirello <cicirello@users.noreply.github.com>
        branch: create-pull-request/badge
        delete-branch: true
        labels: |
          automated
